Ejercicio 2
Joelit0/Gist pull request #2
Opened 2020-02-20 11:17 UTC by JoelAlayon123

Exercise 2 is similar to Exercise 1 but is now able to receive a directory path. Now the user can put a directory path that contains subfolders or a simple file.

2020-03-25 13:12 UTC, pazcuturi commented on Ejercicio5b.rb
> +    filename= gets.chomp
add missing space please

2020-03-25 13:12 UTC, pazcuturi commented on Ejercicio5b.rb
> +      if response_status== "201"
add missing space please

2020-03-25 13:12 UTC, pazcuturi commented on Ejercicio5b.rb
> +      @bar ={ :description => description,:public => state,:files =>{} }
add missing space please

2020-03-25 13:12 UTC, pazcuturi commented on Ejercicio5b.rb
> +      response_status = "#{response.code}"
Why interpolate this when you can use an integer instead?

2020-03-25 13:12 UTC, pazcuturi commented on Gist_Request.rb
> +    request.body = JSON.dump({ "description" => @description,"public" => @state,"files" => { @filename => { "content" => @content }}})
add spaces after comma please

2020-03-25 13:12 UTC, pazcuturi commented on Gist_Request.rb
> +    @response_status = response.code
Same here, why use string interpolation when you can use the integer instead?

2020-03-25 13:12 UTC, pazcuturi commented on Main.rb
> +  state= gets.chomp.capitalize
add missing space please

2020-03-25 19:55 UTC, jrgonh requested changes

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +      end
state = state != "No"

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +      puts"---Quieres que tu repositorio sea publico?---"
---Quieres que tu repositorio sea público? Si/No, por defecto el repositorio será público---

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +      if response_status== "201"
HTTP_STATUS_CREATED = "201"

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +      end
same as above

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +        open(f, "r:UTF-8") do |file| # Leer el contenido del archivo
comments in english

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +      if response_status == "201"
use constants

2020-03-25 19:55 UTC, jrgonh commented on Ejercicio5b.rb
> +end
add newline

2020-03-31 16:50 UTC, jrgonh approved these changes

2020-03-31 17:04 UTC, merged